a32nx briefing:
  - changed-files:
      - any-glob-to-any-file: docs/pilots-corner/a32nx-briefing/**/*

beginner guide:
  - changed-files:
      - any-glob-to-any-file: docs/pilots-corner/beginner-guide/**/*

advanced guides:
  - changed-files:
      - any-glob-to-any-file: docs/pilots-corner/advanced-guides/**/*

feature guide:
  - changed-files:
      - any-glob-to-any-file: docs/fbw-a32nx/feature-guides/**/*

support:
  - changed-files:
      - any-glob-to-any-file: docs/fbw-a32nx/support/*

simbridge:
  - changed-files:
      - any-glob-to-any-file: docs/simbridge/*

repo:
  - changed-files:
      - any-glob-to-any-file: '*'
