name: PR Title
on:
  pull_request_target:
    types: [opened, reopened, synchronize, ready_for_review, edited]

jobs:
  title:
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v3.4.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}